### ISSUE TITLE
rayo-routing.properties changes require restart on gateway

### ISSUE THREAD

**Issue by johntdyer** [rayo/rayo-server#11] opened 2011-11-08 15:48 UTC
[jdyer@rayo-gw111 ~]$ cat /opt/voxeo/prism/apps/rayo-gateway/META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: voxeohudson
Build-Jdk: 1.6.0_25
Build-Id: 2011-10-27_16-29-18
Hudson-Build-Number: 555
Hudson-Project: Rayo
Hudson-Version: 2.0.0
Implementation-Version: hudson-Rayo-555
Specification-Title: Rayo Gateway
Specification-Version: 2.0-SNAPSHOT

Changes were not active until the app server was restarted

**Comment by benlangfeld** [comment] 2011-11-08 15:49
Duplicate of #7

**Closed as completed** 2011-11-08 16:22 UTC
