### ISSUE TITLE
Output fails in a strange way

### ISSUE THREAD

**Issue by benlangfeld** [rayo/rayo-server#19] opened 2012-03-19 23:04 UTC
https://gist.github.com/a656815535601c5daed1

Are we doing something wrong here? Does the <speak/> need to be in CDATA?

**Comment by mpermar** [comment] 2012-03-20 06:57
I assume the SSML  you are sending is 

`xml <speak version="1.0" xmlns:xml="" xml:xml:lang="en-US"><audio src="digits/3"/></speak>`

I think there is a couple of mistakes in there. Reassigning the xml namespace is forbidden (http://www.w3.org/TR/REC-xml-names/#xmlReserved). Also I'd say xml:xml:lang will give you a syntax error, should be xml:lang

**Comment by benlangfeld** [comment] 2012-03-20 09:09
That's not correct. rayo-server is doing that butchering. The SSML doc we send is here: https://gist.github.com/a656815535601c5daed1#file_wire.xml

I suspect rayo-server is expecting this to be CDATA, no? On the other hand, a very similar SSML doc (as can be seen in the gist) works, where the only difference is a valid URI in the `<audio/>` tag.

**Comment by mpermar** [comment] 2012-03-20 09:37
Right. mmm. Interesting. The Prism log you got there in the gist is a bit incomplete. I'd like to see a few lines before of what is in there to check what is really entering into Prism. Is there any chance to upload that?

**Comment by benlangfeld** [comment] 2012-03-20 09:38
Sure, I'll run a fresh log.

**Comment by benlangfeld** [comment] 2012-03-20 09:53
Fresh logs from both Adhearsion and PRISM showing several scenarios: https://gist.github.com/2133592

**Comment by mpermar** [comment] 2012-03-20 16:16
This is fixed now. I already mentioned on the chat but keeping it here for the record. The command you are sending it is going to fail anyways as the spec specifies that whatever is within src element it has to be a resource URI. 

So the problem is that even though this bug is fixed, when you send the <audio src="digits/3"/> element you are going to get an error like this one:

`<complete xmlns="urn:xmpp:rayo:ext:1">
         <error xmlns="urn:xmpp:rayo:ext:complete:1">Could not find the Resource's URI</error>
     </complete>`

**Closed as completed by mpermar** 2012-03-20 16:16 UTC

**Comment by benlangfeld** [comment] 2012-03-20 16:17
Lovely, that error is a lot more useful. Thanks Martin.
